# Generated by Django 6.0 on 2026-06-30 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prompts", "0002_prompt_model_used_allowedemail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prompt",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("public", "Public - All EarthRISE users"),
                    ("domain", "Domain - Only domain members"),
                    ("private", "Private - Only me"),
                ],
                default="public",
                max_length=10,
            ),
        ),
    ]
